export function rando(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function getFunName() {
  const fears = ['Wear the strangest outfit from your wardrobe in the streets',
                 'Talk to 5 strangers today',
                 'Stay up and stare at the stars for 30 mins',
                 'Purchase tickets (airplane, bus, train) to somewhere you have never gone before',
                 'Donate $10 to a cause of your desire',
                 'Smile at 5 people',
                 'Hug 5 random people',
                 'Call your father',
                 'Call one of your siblings',
                 'Dance to your favorite song and scream the lyrics outloud',
                 'Smile and look at 5 people in the eyes',
                 'Buy a coffee for the person behind you in line',
                 'Sign up to volunteer at an event...today',
                 'Give someone you barely know a hug',
                 'Take your camera out and photograph the world for 1 hour',
                 'Sign up to volunteer somewhere for 1 hour (if not today, this week)',
                 'Make cookies for a neighbor',
                 'Sign up for an event/go to a networking event',
                 'Send in an appication for something (a job, university, other program)',
                 'Talk to a stranger for 10 minutes',
                 'Surprise someone with a special treat',
                 'Spend 30 minutes learning a new language',
                 'Draw or paint for 1 hour',
                 'Begin learning a new skill',
                 'Call someone you are nervous to make a call to',
                 'Go to a networking event',
                 'Flirt with someone',
                 'Talk to 5 random strangers',
                 'Ask the nearest person to you at this moment for something',
                 'Tell someone they are pretty/handsome',
                 'Find one inspiring person and call or write them',
                 'Turn off your phone for the whole day (or if impossible, then once this week',
                 'Call a childhood friend',
                 'Put your phone in airplane mode for the whole day',
                 'Take your partner (or someone special) out on a date tonight',
                 'Go for a twenty minute walk in a direction you normally don’t go in',
                 'Sign up for a competition (i.e. a 5k, Spartacus run...even better if it is for charity)',
                 'Take a different method or route to work/school/wherever today and take note of the interesting things along the way',
                 'Spend 30 minutes drawing today',
                 'Spend 30 minutes writing about whatever today',
                 'Sign up to study a new language or course today',
                 'Get your running shoes on and go for a mind-clearing jog',
                 'Apply to a new opportunity today',
                 'If you haven’t started yet, start meditating for 30 days today (Headspace is a great app)',
                 'Open the door for someone every time you go through a door today',
                 'Buy a stranger a flower',
                 'Do a chore for someone without them noticing',
                 'Do something nice for your neighbor (bake something or just send them a nice note)',
                 'Wherever you are, find some local postcards and send three with heartfelt messages on them to someone you know',
                 'Leave some kind notes on people’s cars with encouraging messages',
                 'Depending on the weather, give warm or cold drinks out to those who are braving the outdoors for the day',
                 'Spend 20 minutes picking up garbage from somewhere today (BONUS: Try to get others to join you)',
                 'Compliment 3 strangers',
                 'Call an old friend',
                 'Send five friends or family members messages about their strongest qualities to boost their confidence',
                 'Make your partner or someone breakfast in bed (or a friend or roommate if you are singling these days)',
                 'Put away google maps and ask strangers for directions today. Practice on 3 people.',
                 'Starting today, for one month, track how much you are spending and begin changing your financial habits',
                 'Speak up in a meeting today and voice your opinion',
                 'Stand up to someone who has been pushing you to your limits',
                 'Hypothetically, if you were to die tomorrow, do something today that you would regret you didn’t do otherwise',
                 'Attend a networking event',
                 'Get somebody’s phone number today',
                 'Get your voice out there today (an opinion, your music, your love for someone) in whatever way (message, video, in-person)',
                 'Identify your biggest phobia and do something today to fix it',
                 'Come up with an idea (or an existing idea) and tell two people about it asking for feedback',
                 'Make a three course meal from scratch for someone you have never cooked for before',
                 'give a book you love to a stranger',
                 'give some food to a homeless person',
                 'go skinny dipping in a lake',
                 'give three compliments to a stranger - it has to be the same person for all three',
                 'throw a surprise party,',
                 'buy a stranger a drink',
                 'book a flight the day before you travel and go on a spontaneous adventure',
                 'get on a national train and take it to the end of the line',
                 'have sex in a place you have never had sex before',
                 'write someone you love a rainy day letter',
                 'crash a wedding',
                 'speak only a non-mother tongue language for the whole day',
                 'send a driend a message telling him or her all the good things you like about him or her'];

  const generatedMessage = `${rando(fears)}`
  return generatedMessage;
}
